### ISSUE TITLE
Adding a new document with the same song id doesn't remove the old document(s) for that song id in the collection

### ISSUE THREAD

**Issue by Areedtz** [nsst19/Seven-Sidekicks-Project#8]
Using insert on any of the database clients doesn't seem to remove the old entries for that song id.

I think it would make sense to remove old entries for a song id. Unless we want to only return the newest document for that song id.

**Comment by mikkelkai** [comment]
I was thinking that we would just return the newest entry and keep a record of historical values. But i'm open to deleting them as well.
Either way it should be a relatively small change :)

**Comment by mikkelkai** [comment]
Solved by #9
